package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bophan generated by hbm2java
 */
public class Bophan  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private String ghichu;
     private Boolean activity;
     private Set nhanviens = new HashSet(0);

    public Bophan() {
    }

    public Bophan(String ma, String ten, String ghichu, Boolean activity, Set nhanviens) {
       this.ma = ma;
       this.ten = ten;
       this.ghichu = ghichu;
       this.activity = activity;
       this.nhanviens = nhanviens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


