package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1



/**
 * Chitietphieuxuat generated by hbm2java
 */
public class Chitietphieuxuat  implements java.io.Serializable {


     private Integer id;
     private Hanghoa hanghoa;
     private Phieuxuat phieuxuat;
     private String ma;
     private Integer soluong;
     private Double dongia;
     private Double thanhtien;
     private Boolean activite;

    public Chitietphieuxuat() {
    }

    public Chitietphieuxuat(Hanghoa hanghoa, Phieuxuat phieuxuat, String ma, Integer soluong, Double dongia, Double thanhtien, Boolean activite) {
       this.hanghoa = hanghoa;
       this.phieuxuat = phieuxuat;
       this.ma = ma;
       this.soluong = soluong;
       this.dongia = dongia;
       this.thanhtien = thanhtien;
       this.activite = activite;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Hanghoa getHanghoa() {
        return this.hanghoa;
    }
    
    public void setHanghoa(Hanghoa hanghoa) {
        this.hanghoa = hanghoa;
    }
    public Phieuxuat getPhieuxuat() {
        return this.phieuxuat;
    }
    
    public void setPhieuxuat(Phieuxuat phieuxuat) {
        this.phieuxuat = phieuxuat;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Double getDongia() {
        return this.dongia;
    }
    
    public void setDongia(Double dongia) {
        this.dongia = dongia;
    }
    public Double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(Double thanhtien) {
        this.thanhtien = thanhtien;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }




}


