package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1



/**
 * Chitietphieunhap generated by hbm2java
 */
public class Chitietphieunhap  implements java.io.Serializable {


     private Integer id;
     private Hanghoa hanghoa;
     private Phieunhap phieunhap;
     private Integer soluong;
     private Double dongia;
     private Double thanhtien;
     private String ghichu;
     private Boolean activity;
     private String ma;

    public Chitietphieunhap() {
    }

    public Chitietphieunhap(Hanghoa hanghoa, Phieunhap phieunhap, Integer soluong, Double dongia, Double thanhtien, String ghichu, Boolean activity, String ma) {
       this.hanghoa = hanghoa;
       this.phieunhap = phieunhap;
       this.soluong = soluong;
       this.dongia = dongia;
       this.thanhtien = thanhtien;
       this.ghichu = ghichu;
       this.activity = activity;
       this.ma = ma;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Hanghoa getHanghoa() {
        return this.hanghoa;
    }
    
    public void setHanghoa(Hanghoa hanghoa) {
        this.hanghoa = hanghoa;
    }
    public Phieunhap getPhieunhap() {
        return this.phieunhap;
    }
    
    public void setPhieunhap(Phieunhap phieunhap) {
        this.phieunhap = phieunhap;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Double getDongia() {
        return this.dongia;
    }
    
    public void setDongia(Double dongia) {
        this.dongia = dongia;
    }
    public Double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(Double thanhtien) {
        this.thanhtien = thanhtien;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }




}


