package com.qlbh.pojo;
// Generated 26/10/2016 3:07:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietchuyenkho generated by hbm2java
 */
@Entity
@Table(name="chitietchuyenkho"
    ,catalog="qlbh"
)
public class Chitietchuyenkho  implements java.io.Serializable {


     private Integer id;
     private Chuyenkho chuyenkho;
     private Hanghoa hanghoa;
     private String ma;
     private Integer soluong;
     private Double dongia;
     private Double thanhtien;
     private Boolean activity;

    public Chitietchuyenkho() {
    }

    public Chitietchuyenkho(Chuyenkho chuyenkho, Hanghoa hanghoa, String ma, Integer soluong, Double dongia, Double thanhtien, Boolean activity) {
       this.chuyenkho = chuyenkho;
       this.hanghoa = hanghoa;
       this.ma = ma;
       this.soluong = soluong;
       this.dongia = dongia;
       this.thanhtien = thanhtien;
       this.activity = activity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="chuyenkhoid")
    public Chuyenkho getChuyenkho() {
        return this.chuyenkho;
    }
    
    public void setChuyenkho(Chuyenkho chuyenkho) {
        this.chuyenkho = chuyenkho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hanghoaid")
    public Hanghoa getHanghoa() {
        return this.hanghoa;
    }
    
    public void setHanghoa(Hanghoa hanghoa) {
        this.hanghoa = hanghoa;
    }

    
    @Column(name="ma")
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="soluong")
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }

    
    @Column(name="dongia", precision=22, scale=0)
    public Double getDongia() {
        return this.dongia;
    }
    
    public void setDongia(Double dongia) {
        this.dongia = dongia;
    }

    
    @Column(name="thanhtien", precision=22, scale=0)
    public Double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(Double thanhtien) {
        this.thanhtien = thanhtien;
    }

    
    @Column(name="activity")
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }




}


