package com.qlbh.pojo;
// Generated 21/09/2016 2:16:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietphieunhap generated by hbm2java
 */
@Entity
@Table(name="chitietphieunhap"
    ,catalog="qlbh"
)
public class Chitietphieunhap  implements java.io.Serializable {


     private int ma;
     private Hanghoa hanghoa;
     private Phieunhap phieunhap;
     private Integer soluong;
     private Double dongia;
     private Double thanhtien;
     private String ghichu;
     private Byte activite;

    public Chitietphieunhap() {
    }

	
    public Chitietphieunhap(int ma) {
        this.ma = ma;
    }
    public Chitietphieunhap(int ma, Hanghoa hanghoa, Phieunhap phieunhap, Integer soluong, Double dongia, Double thanhtien, String ghichu, Byte activite) {
       this.ma = ma;
       this.hanghoa = hanghoa;
       this.phieunhap = phieunhap;
       this.soluong = soluong;
       this.dongia = dongia;
       this.thanhtien = thanhtien;
       this.ghichu = ghichu;
       this.activite = activite;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mahanghoa")
    public Hanghoa getHanghoa() {
        return this.hanghoa;
    }
    
    public void setHanghoa(Hanghoa hanghoa) {
        this.hanghoa = hanghoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maphieunhap")
    public Phieunhap getPhieunhap() {
        return this.phieunhap;
    }
    
    public void setPhieunhap(Phieunhap phieunhap) {
        this.phieunhap = phieunhap;
    }

    
    @Column(name="soluong")
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }

    
    @Column(name="dongia", precision=22, scale=0)
    public Double getDongia() {
        return this.dongia;
    }
    
    public void setDongia(Double dongia) {
        this.dongia = dongia;
    }

    
    @Column(name="thanhtien", precision=22, scale=0)
    public Double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(Double thanhtien) {
        this.thanhtien = thanhtien;
    }

    
    @Column(name="ghichu")
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }




}


