package com.qlbh.pojo;
// Generated 21/09/2016 7:11:19 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Donvitinh generated by hbm2java
 */
@Entity
@Table(name="donvitinh"
    ,catalog="qlbh"
)
public class Donvitinh  implements java.io.Serializable {


     private int ma;
     private String ten;
     private String ghichu;
     private Byte activite;

    public Donvitinh() {
    }

	
    public Donvitinh(int ma) {
        this.ma = ma;
    }
    public Donvitinh(int ma, String ten, String ghichu, Byte activite) {
       this.ma = ma;
       this.ten = ten;
       this.ghichu = ghichu;
       this.activite = activite;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="ghichu")
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }




}


