package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hanghoa generated by hbm2java
 */
public class Hanghoa  implements java.io.Serializable {


     private Integer id;
     private Donvitinh donvitinh;
     private Khohang khohang;
     private Loaihang loaihang;
     private Nhacungcap nhacungcap;
     private Nhomhanghoa nhomhanghoa;
     private String ma;
     private String ten;
     private String xuatxu;
     private Double giamua;
     private Double giabanle;
     private Double giabansi;
     private Integer tonkho;
     private String anh;
     private Boolean activity;
     private Set chitietphieunhaps = new HashSet(0);
     private Set chitietphieuxuats = new HashSet(0);

    public Hanghoa() {
    }

    public Hanghoa(Donvitinh donvitinh, Khohang khohang, Loaihang loaihang, Nhacungcap nhacungcap, Nhomhanghoa nhomhanghoa, String ma, String ten, String xuatxu, Double giamua, Double giabanle, Double giabansi, Integer tonkho, String anh, Boolean activity, Set chitietphieunhaps, Set chitietphieuxuats) {
       this.donvitinh = donvitinh;
       this.khohang = khohang;
       this.loaihang = loaihang;
       this.nhacungcap = nhacungcap;
       this.nhomhanghoa = nhomhanghoa;
       this.ma = ma;
       this.ten = ten;
       this.xuatxu = xuatxu;
       this.giamua = giamua;
       this.giabanle = giabanle;
       this.giabansi = giabansi;
       this.tonkho = tonkho;
       this.anh = anh;
       this.activity = activity;
       this.chitietphieunhaps = chitietphieunhaps;
       this.chitietphieuxuats = chitietphieuxuats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Donvitinh getDonvitinh() {
        return this.donvitinh;
    }
    
    public void setDonvitinh(Donvitinh donvitinh) {
        this.donvitinh = donvitinh;
    }
    public Khohang getKhohang() {
        return this.khohang;
    }
    
    public void setKhohang(Khohang khohang) {
        this.khohang = khohang;
    }
    public Loaihang getLoaihang() {
        return this.loaihang;
    }
    
    public void setLoaihang(Loaihang loaihang) {
        this.loaihang = loaihang;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Nhomhanghoa getNhomhanghoa() {
        return this.nhomhanghoa;
    }
    
    public void setNhomhanghoa(Nhomhanghoa nhomhanghoa) {
        this.nhomhanghoa = nhomhanghoa;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getXuatxu() {
        return this.xuatxu;
    }
    
    public void setXuatxu(String xuatxu) {
        this.xuatxu = xuatxu;
    }
    public Double getGiamua() {
        return this.giamua;
    }
    
    public void setGiamua(Double giamua) {
        this.giamua = giamua;
    }
    public Double getGiabanle() {
        return this.giabanle;
    }
    
    public void setGiabanle(Double giabanle) {
        this.giabanle = giabanle;
    }
    public Double getGiabansi() {
        return this.giabansi;
    }
    
    public void setGiabansi(Double giabansi) {
        this.giabansi = giabansi;
    }
    public Integer getTonkho() {
        return this.tonkho;
    }
    
    public void setTonkho(Integer tonkho) {
        this.tonkho = tonkho;
    }
    public String getAnh() {
        return this.anh;
    }
    
    public void setAnh(String anh) {
        this.anh = anh;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public Set getChitietphieunhaps() {
        return this.chitietphieunhaps;
    }
    
    public void setChitietphieunhaps(Set chitietphieunhaps) {
        this.chitietphieunhaps = chitietphieunhaps;
    }
    public Set getChitietphieuxuats() {
        return this.chitietphieuxuats;
    }
    
    public void setChitietphieuxuats(Set chitietphieuxuats) {
        this.chitietphieuxuats = chitietphieuxuats;
    }




}


