package com.qlbh.pojo;
// Generated 21/09/2016 7:11:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hanghoa generated by hbm2java
 */
@Entity
@Table(name="hanghoa"
    ,catalog="qlbh"
)
public class Hanghoa  implements java.io.Serializable {


     private int ma;
     private Khohang khohang;
     private Loaihang loaihang;
     private Nhacungcap nhacungcap;
     private Nhomhanghoa nhomhanghoa;
     private String ten;
     private String donvi;
     private String xuatxu;
     private Double giamua;
     private Double giabanle;
     private Double giabansi;
     private Integer tonkho;
     private byte[] anh;
     private Byte activite;
     private Set<Chitietphieuxuat> chitietphieuxuats = new HashSet<Chitietphieuxuat>(0);
     private Set<Chitietphieunhap> chitietphieunhaps = new HashSet<Chitietphieunhap>(0);

    public Hanghoa() {
    }

	
    public Hanghoa(int ma) {
        this.ma = ma;
    }
    public Hanghoa(int ma, Khohang khohang, Loaihang loaihang, Nhacungcap nhacungcap, Nhomhanghoa nhomhanghoa, String ten, String donvi, String xuatxu, Double giamua, Double giabanle, Double giabansi, Integer tonkho, byte[] anh, Byte activite, Set<Chitietphieuxuat> chitietphieuxuats, Set<Chitietphieunhap> chitietphieunhaps) {
       this.ma = ma;
       this.khohang = khohang;
       this.loaihang = loaihang;
       this.nhacungcap = nhacungcap;
       this.nhomhanghoa = nhomhanghoa;
       this.ten = ten;
       this.donvi = donvi;
       this.xuatxu = xuatxu;
       this.giamua = giamua;
       this.giabanle = giabanle;
       this.giabansi = giabansi;
       this.tonkho = tonkho;
       this.anh = anh;
       this.activite = activite;
       this.chitietphieuxuats = chitietphieuxuats;
       this.chitietphieunhaps = chitietphieunhaps;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="makhohang")
    public Khohang getKhohang() {
        return this.khohang;
    }
    
    public void setKhohang(Khohang khohang) {
        this.khohang = khohang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maloaihang")
    public Loaihang getLoaihang() {
        return this.loaihang;
    }
    
    public void setLoaihang(Loaihang loaihang) {
        this.loaihang = loaihang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manhacc")
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manhomhang")
    public Nhomhanghoa getNhomhanghoa() {
        return this.nhomhanghoa;
    }
    
    public void setNhomhanghoa(Nhomhanghoa nhomhanghoa) {
        this.nhomhanghoa = nhomhanghoa;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="donvi")
    public String getDonvi() {
        return this.donvi;
    }
    
    public void setDonvi(String donvi) {
        this.donvi = donvi;
    }

    
    @Column(name="xuatxu")
    public String getXuatxu() {
        return this.xuatxu;
    }
    
    public void setXuatxu(String xuatxu) {
        this.xuatxu = xuatxu;
    }

    
    @Column(name="giamua", precision=22, scale=0)
    public Double getGiamua() {
        return this.giamua;
    }
    
    public void setGiamua(Double giamua) {
        this.giamua = giamua;
    }

    
    @Column(name="giabanle", precision=22, scale=0)
    public Double getGiabanle() {
        return this.giabanle;
    }
    
    public void setGiabanle(Double giabanle) {
        this.giabanle = giabanle;
    }

    
    @Column(name="giabansi", precision=22, scale=0)
    public Double getGiabansi() {
        return this.giabansi;
    }
    
    public void setGiabansi(Double giabansi) {
        this.giabansi = giabansi;
    }

    
    @Column(name="tonkho")
    public Integer getTonkho() {
        return this.tonkho;
    }
    
    public void setTonkho(Integer tonkho) {
        this.tonkho = tonkho;
    }

    
    @Column(name="anh")
    public byte[] getAnh() {
        return this.anh;
    }
    
    public void setAnh(byte[] anh) {
        this.anh = anh;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hanghoa")
    public Set<Chitietphieuxuat> getChitietphieuxuats() {
        return this.chitietphieuxuats;
    }
    
    public void setChitietphieuxuats(Set<Chitietphieuxuat> chitietphieuxuats) {
        this.chitietphieuxuats = chitietphieuxuats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hanghoa")
    public Set<Chitietphieunhap> getChitietphieunhaps() {
        return this.chitietphieunhaps;
    }
    
    public void setChitietphieunhaps(Set<Chitietphieunhap> chitietphieunhaps) {
        this.chitietphieunhaps = chitietphieunhaps;
    }




}


