package com.qlbh.pojo;
// Generated 25/10/2016 11:21:04 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Keeplogged generated by hbm2java
 */
@Entity
@Table(name="keeplogged"
    ,catalog="qlbh"
)
public class Keeplogged  implements java.io.Serializable {


     private Integer id;
     private String usename;
     private String pass;

    public Keeplogged() {
    }

    public Keeplogged(String usename, String pass) {
       this.usename = usename;
       this.pass = pass;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="usename")
    public String getUsename() {
        return this.usename;
    }
    
    public void setUsename(String usename) {
        this.usename = usename;
    }

    
    @Column(name="pass")
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


