package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private Integer id;
     private Khuvuc khuvuc;
     private Loaikhachhang loaikhachhang;
     private String ma;
     private String makh;
     private String ten;
     private String diachi;
     private String masothue;
     private String dienthoai;
     private String email;
     private String taikhoan;
     private String nganhang;
     private BigDecimal gioihanno;
     private BigDecimal nohientai;
     private String yahoo;
     private String skype;
     private String nguoilienhe;
     private Boolean activite;
     private Set phieuxuats = new HashSet(0);

    public Khachhang() {
    }

    public Khachhang(Khuvuc khuvuc, Loaikhachhang loaikhachhang, String ma, String makh, String ten, String diachi, String masothue, String dienthoai, String email, String taikhoan, String nganhang, BigDecimal gioihanno, BigDecimal nohientai, String yahoo, String skype, String nguoilienhe, Boolean activite, Set phieuxuats) {
       this.khuvuc = khuvuc;
       this.loaikhachhang = loaikhachhang;
       this.ma = ma;
       this.makh = makh;
       this.ten = ten;
       this.diachi = diachi;
       this.masothue = masothue;
       this.dienthoai = dienthoai;
       this.email = email;
       this.taikhoan = taikhoan;
       this.nganhang = nganhang;
       this.gioihanno = gioihanno;
       this.nohientai = nohientai;
       this.yahoo = yahoo;
       this.skype = skype;
       this.nguoilienhe = nguoilienhe;
       this.activite = activite;
       this.phieuxuats = phieuxuats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Khuvuc getKhuvuc() {
        return this.khuvuc;
    }
    
    public void setKhuvuc(Khuvuc khuvuc) {
        this.khuvuc = khuvuc;
    }
    public Loaikhachhang getLoaikhachhang() {
        return this.loaikhachhang;
    }
    
    public void setLoaikhachhang(Loaikhachhang loaikhachhang) {
        this.loaikhachhang = loaikhachhang;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getMakh() {
        return this.makh;
    }
    
    public void setMakh(String makh) {
        this.makh = makh;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getMasothue() {
        return this.masothue;
    }
    
    public void setMasothue(String masothue) {
        this.masothue = masothue;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(String taikhoan) {
        this.taikhoan = taikhoan;
    }
    public String getNganhang() {
        return this.nganhang;
    }
    
    public void setNganhang(String nganhang) {
        this.nganhang = nganhang;
    }
    public BigDecimal getGioihanno() {
        return this.gioihanno;
    }
    
    public void setGioihanno(BigDecimal gioihanno) {
        this.gioihanno = gioihanno;
    }
    public BigDecimal getNohientai() {
        return this.nohientai;
    }
    
    public void setNohientai(BigDecimal nohientai) {
        this.nohientai = nohientai;
    }
    public String getYahoo() {
        return this.yahoo;
    }
    
    public void setYahoo(String yahoo) {
        this.yahoo = yahoo;
    }
    public String getSkype() {
        return this.skype;
    }
    
    public void setSkype(String skype) {
        this.skype = skype;
    }
    public String getNguoilienhe() {
        return this.nguoilienhe;
    }
    
    public void setNguoilienhe(String nguoilienhe) {
        this.nguoilienhe = nguoilienhe;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }
    public Set getPhieuxuats() {
        return this.phieuxuats;
    }
    
    public void setPhieuxuats(Set phieuxuats) {
        this.phieuxuats = phieuxuats;
    }




}


