package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khohang generated by hbm2java
 */
public class Khohang  implements java.io.Serializable {


     private Integer id;
     private Nhanvien nhanvien;
     private String ma;
     private String ten;
     private String nguoilienhe;
     private String diachi;
     private String dienthoai;
     private String email;
     private String fax;
     private String diengiai;
     private Boolean activity;
     private Set phieuxuats = new HashSet(0);
     private Set hanghoas = new HashSet(0);
     private Set phieunhaps = new HashSet(0);

    public Khohang() {
    }

    public Khohang(Nhanvien nhanvien, String ma, String ten, String nguoilienhe, String diachi, String dienthoai, String email, String fax, String diengiai, Boolean activity, Set phieuxuats, Set hanghoas, Set phieunhaps) {
       this.nhanvien = nhanvien;
       this.ma = ma;
       this.ten = ten;
       this.nguoilienhe = nguoilienhe;
       this.diachi = diachi;
       this.dienthoai = dienthoai;
       this.email = email;
       this.fax = fax;
       this.diengiai = diengiai;
       this.activity = activity;
       this.phieuxuats = phieuxuats;
       this.hanghoas = hanghoas;
       this.phieunhaps = phieunhaps;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getNguoilienhe() {
        return this.nguoilienhe;
    }
    
    public void setNguoilienhe(String nguoilienhe) {
        this.nguoilienhe = nguoilienhe;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getDiengiai() {
        return this.diengiai;
    }
    
    public void setDiengiai(String diengiai) {
        this.diengiai = diengiai;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public Set getPhieuxuats() {
        return this.phieuxuats;
    }
    
    public void setPhieuxuats(Set phieuxuats) {
        this.phieuxuats = phieuxuats;
    }
    public Set getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set hanghoas) {
        this.hanghoas = hanghoas;
    }
    public Set getPhieunhaps() {
        return this.phieunhaps;
    }
    
    public void setPhieunhaps(Set phieunhaps) {
        this.phieunhaps = phieunhaps;
    }




}


