package com.qlbh.pojo;
// Generated 21/09/2016 7:11:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khohang generated by hbm2java
 */
@Entity
@Table(name="khohang"
    ,catalog="qlbh"
)
public class Khohang  implements java.io.Serializable {


     private int ma;
     private Nhanvien nhanvien;
     private String ten;
     private String nguoilienhe;
     private String diachi;
     private String dienthoai;
     private String email;
     private String fax;
     private String diengiai;
     private Byte activite;
     private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);
     private Set<Phieuxuat> phieuxuats = new HashSet<Phieuxuat>(0);
     private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);

    public Khohang() {
    }

	
    public Khohang(int ma) {
        this.ma = ma;
    }
    public Khohang(int ma, Nhanvien nhanvien, String ten, String nguoilienhe, String diachi, String dienthoai, String email, String fax, String diengiai, Byte activite, Set<Hanghoa> hanghoas, Set<Phieuxuat> phieuxuats, Set<Phieunhap> phieunhaps) {
       this.ma = ma;
       this.nhanvien = nhanvien;
       this.ten = ten;
       this.nguoilienhe = nguoilienhe;
       this.diachi = diachi;
       this.dienthoai = dienthoai;
       this.email = email;
       this.fax = fax;
       this.diengiai = diengiai;
       this.activite = activite;
       this.hanghoas = hanghoas;
       this.phieuxuats = phieuxuats;
       this.phieunhaps = phieunhaps;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manguoiql")
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="nguoilienhe")
    public String getNguoilienhe() {
        return this.nguoilienhe;
    }
    
    public void setNguoilienhe(String nguoilienhe) {
        this.nguoilienhe = nguoilienhe;
    }

    
    @Column(name="diachi")
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    
    @Column(name="dienthoai")
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="fax")
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="diengiai")
    public String getDiengiai() {
        return this.diengiai;
    }
    
    public void setDiengiai(String diengiai) {
        this.diengiai = diengiai;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khohang")
    public Set<Hanghoa> getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set<Hanghoa> hanghoas) {
        this.hanghoas = hanghoas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khohang")
    public Set<Phieuxuat> getPhieuxuats() {
        return this.phieuxuats;
    }
    
    public void setPhieuxuats(Set<Phieuxuat> phieuxuats) {
        this.phieuxuats = phieuxuats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khohang")
    public Set<Phieunhap> getPhieunhaps() {
        return this.phieunhaps;
    }
    
    public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
        this.phieunhaps = phieunhaps;
    }




}


