package com.qlbh.pojo;
// Generated 21/09/2016 2:16:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khuvuc generated by hbm2java
 */
@Entity
@Table(name="khuvuc"
    ,catalog="qlbh"
)
public class Khuvuc  implements java.io.Serializable {


     private int ma;
     private String ten;
     private String ghichu;
     private Byte activite;
     private Set<Nhacungcap> nhacungcaps = new HashSet<Nhacungcap>(0);

    public Khuvuc() {
    }

	
    public Khuvuc(int ma) {
        this.ma = ma;
    }
    public Khuvuc(int ma, String ten, String ghichu, Byte activite, Set<Nhacungcap> nhacungcaps) {
       this.ma = ma;
       this.ten = ten;
       this.ghichu = ghichu;
       this.activite = activite;
       this.nhacungcaps = nhacungcaps;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="ghichu")
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khuvuc")
    public Set<Nhacungcap> getNhacungcaps() {
        return this.nhacungcaps;
    }
    
    public void setNhacungcaps(Set<Nhacungcap> nhacungcaps) {
        this.nhacungcaps = nhacungcaps;
    }




}


