package com.qlbh.pojo;
// Generated 23/09/2016 10:02:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khuvuc generated by hbm2java
 */
@Entity
@Table(name="khuvuc"
    ,catalog="qlbh"
)
public class Khuvuc  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private String ghichu;
     private Boolean activite;
     private Set<Nhacungcap> nhacungcaps = new HashSet<Nhacungcap>(0);
     private Set<Khachhang> khachhangs = new HashSet<Khachhang>(0);

    public Khuvuc() {
    }

    public Khuvuc(String ma, String ten, String ghichu, Boolean activite, Set<Nhacungcap> nhacungcaps, Set<Khachhang> khachhangs) {
       this.ma = ma;
       this.ten = ten;
       this.ghichu = ghichu;
       this.activite = activite;
       this.nhacungcaps = nhacungcaps;
       this.khachhangs = khachhangs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ma", length=20)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="ghichu")
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    
    @Column(name="activite")
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khuvuc")
    public Set<Nhacungcap> getNhacungcaps() {
        return this.nhacungcaps;
    }
    
    public void setNhacungcaps(Set<Nhacungcap> nhacungcaps) {
        this.nhacungcaps = nhacungcaps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="khuvuc")
    public Set<Khachhang> getKhachhangs() {
        return this.khachhangs;
    }
    
    public void setKhachhangs(Set<Khachhang> khachhangs) {
        this.khachhangs = khachhangs;
    }




}


