package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khuvuc generated by hbm2java
 */
public class Khuvuc  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private String ghichu;
     private Boolean activity;
     private Set nhacungcaps = new HashSet(0);
     private Set khachhangs = new HashSet(0);

    public Khuvuc() {
    }

    public Khuvuc(String ma, String ten, String ghichu, Boolean activity, Set nhacungcaps, Set khachhangs) {
       this.ma = ma;
       this.ten = ten;
       this.ghichu = ghichu;
       this.activity = activity;
       this.nhacungcaps = nhacungcaps;
       this.khachhangs = khachhangs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public Set getNhacungcaps() {
        return this.nhacungcaps;
    }
    
    public void setNhacungcaps(Set nhacungcaps) {
        this.nhacungcaps = nhacungcaps;
    }
    public Set getKhachhangs() {
        return this.khachhangs;
    }
    
    public void setKhachhangs(Set khachhangs) {
        this.khachhangs = khachhangs;
    }




}


