package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaikhachhang generated by hbm2java
 */
public class Loaikhachhang  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private String mota;
     private Boolean activite;
     private Set khachhangs = new HashSet(0);

    public Loaikhachhang() {
    }

    public Loaikhachhang(String ma, String ten, String mota, Boolean activite, Set khachhangs) {
       this.ma = ma;
       this.ten = ten;
       this.mota = mota;
       this.activite = activite;
       this.khachhangs = khachhangs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }
    public Set getKhachhangs() {
        return this.khachhangs;
    }
    
    public void setKhachhangs(Set khachhangs) {
        this.khachhangs = khachhangs;
    }




}


