package com.qlbh.pojo;
// Generated 25/10/2016 12:14:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaikhachhang generated by hbm2java
 */
@Entity
@Table(name="loaikhachhang"
    ,catalog="qlbh"
)
public class Loaikhachhang  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private String mota;
     private Boolean activity;
     private Set<Khachhang> khachhangs = new HashSet<Khachhang>(0);

    public Loaikhachhang() {
    }

    public Loaikhachhang(String ma, String ten, String mota, Boolean activity, Set<Khachhang> khachhangs) {
       this.ma = ma;
       this.ten = ten;
       this.mota = mota;
       this.activity = activity;
       this.khachhangs = khachhangs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ma", length=20)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="mota")
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }

    
    @Column(name="activity")
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loaikhachhang")
    public Set<Khachhang> getKhachhangs() {
        return this.khachhangs;
    }
    
    public void setKhachhangs(Set<Khachhang> khachhangs) {
        this.khachhangs = khachhangs;
    }




}


