package com.qlbh.pojo;
// Generated 21/09/2016 7:11:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaikhachhang generated by hbm2java
 */
@Entity
@Table(name="loaikhachhang"
    ,catalog="qlbh"
)
public class Loaikhachhang  implements java.io.Serializable {


     private int ma;
     private String ten;
     private String mota;
     private Byte activite;
     private Set<Khachhang> khachhangs = new HashSet<Khachhang>(0);

    public Loaikhachhang() {
    }

	
    public Loaikhachhang(int ma) {
        this.ma = ma;
    }
    public Loaikhachhang(int ma, String ten, String mota, Byte activite, Set<Khachhang> khachhangs) {
       this.ma = ma;
       this.ten = ten;
       this.mota = mota;
       this.activite = activite;
       this.khachhangs = khachhangs;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="mota")
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loaikhachhang")
    public Set<Khachhang> getKhachhangs() {
        return this.khachhangs;
    }
    
    public void setKhachhangs(Set<Khachhang> khachhangs) {
        this.khachhangs = khachhangs;
    }




}


