package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaihang generated by hbm2java
 */
public class Loaihang  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private Boolean activite;
     private Set hanghoas = new HashSet(0);

    public Loaihang() {
    }

    public Loaihang(String ma, String ten, Boolean activite, Set hanghoas) {
       this.ma = ma;
       this.ten = ten;
       this.activite = activite;
       this.hanghoas = hanghoas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }
    public Set getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set hanghoas) {
        this.hanghoas = hanghoas;
    }




}


