package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaihang generated by hbm2java
 */
public class Loaihang  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ghichu;
     private String ten;
     private Boolean activity;
     private Set hanghoas = new HashSet(0);

    public Loaihang() {
    }

    public Loaihang(String ma, String ghichu, String ten, Boolean activity, Set hanghoas) {
       this.ma = ma;
       this.ghichu = ghichu;
       this.ten = ten;
       this.activity = activity;
       this.hanghoas = hanghoas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public Set getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set hanghoas) {
        this.hanghoas = hanghoas;
    }




}


