package com.qlbh.pojo;
// Generated 25/10/2016 12:14:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaihang generated by hbm2java
 */
@Entity
@Table(name="loaihang"
    ,catalog="qlbh"
)
public class Loaihang  implements java.io.Serializable {


     @Override
	public String toString() {
		// TODO Auto-generated method stub
		return ten;
	}

	private Integer id;
     private String ma;
     private String ghichu;
     private String ten;
     private Boolean activity;
     private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);

    public Loaihang() {
    }

    public Loaihang(String ma, String ghichu, String ten, Boolean activity, Set<Hanghoa> hanghoas) {
       this.ma = ma;
       this.ghichu = ghichu;
       this.ten = ten;
       this.activity = activity;
       this.hanghoas = hanghoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ma", length=20)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="ghichu", length=65535)
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="activity")
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="loaihang")
    public Set<Hanghoa> getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set<Hanghoa> hanghoas) {
        this.hanghoas = hanghoas;
    }




}


