package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1



/**
 * Nguoidung generated by hbm2java
 */
public class Nguoidung  implements java.io.Serializable {


     private Integer id;
     private Nhanvien nhanvien;
     private Vaitro vaitro;
     private String mand;
     private String tennd;
     private String matkhau;
     private String diengiai;
     private Boolean activity;

    public Nguoidung() {
    }

    public Nguoidung(Nhanvien nhanvien, Vaitro vaitro, String mand, String tennd, String matkhau, String diengiai, Boolean activity) {
       this.nhanvien = nhanvien;
       this.vaitro = vaitro;
       this.mand = mand;
       this.tennd = tennd;
       this.matkhau = matkhau;
       this.diengiai = diengiai;
       this.activity = activity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Vaitro getVaitro() {
        return this.vaitro;
    }
    
    public void setVaitro(Vaitro vaitro) {
        this.vaitro = vaitro;
    }
    public String getMand() {
        return this.mand;
    }
    
    public void setMand(String mand) {
        this.mand = mand;
    }
    public String getTennd() {
        return this.tennd;
    }
    
    public void setTennd(String tennd) {
        this.tennd = tennd;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getDiengiai() {
        return this.diengiai;
    }
    
    public void setDiengiai(String diengiai) {
        this.diengiai = diengiai;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }




}


