package com.qlbh.pojo;
// Generated 23/09/2016 10:02:27 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name="nguoidung"
    ,catalog="qlbh"
)
public class Nguoidung  implements java.io.Serializable {


     private Integer id;
     private Nhanvien nhanvien;
     private Vaitro vaitro;
     private String mand;
     private String tennd;
     private String matkhau;
     private String diengiai;
     private Boolean activite;

    public Nguoidung() {
    }

    public Nguoidung(Nhanvien nhanvien, Vaitro vaitro, String mand, String tennd, String matkhau, String diengiai, Boolean activite) {
       this.nhanvien = nhanvien;
       this.vaitro = vaitro;
       this.mand = mand;
       this.tennd = tennd;
       this.matkhau = matkhau;
       this.diengiai = diengiai;
       this.activite = activite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nhanvienid")
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vaitroid")
    public Vaitro getVaitro() {
        return this.vaitro;
    }
    
    public void setVaitro(Vaitro vaitro) {
        this.vaitro = vaitro;
    }

    
    @Column(name="mand", length=20)
    public String getMand() {
        return this.mand;
    }
    
    public void setMand(String mand) {
        this.mand = mand;
    }

    
    @Column(name="tennd")
    public String getTennd() {
        return this.tennd;
    }
    
    public void setTennd(String tennd) {
        this.tennd = tennd;
    }

    
    @Column(name="matkhau")
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }

    
    @Column(name="diengiai")
    public String getDiengiai() {
        return this.diengiai;
    }
    
    public void setDiengiai(String diengiai) {
        this.diengiai = diengiai;
    }

    
    @Column(name="activite")
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }




}


