package com.qlbh.pojo;
// Generated 24/09/2016 4:28:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name = "nhacungcap", catalog = "qlbh")
public class Nhacungcap implements java.io.Serializable {

	private Integer id;
	private Khuvuc khuvuc;
	private String ma;
	private String ten;
	private String diachi;
	private String masothue;
	private String fax;
	private String tel;
	private String email;
	private String website;
	private String taikhoan;
	private String nganhang;
	private String manguoilienhe;
	private String chucvu;
	private Boolean activite;
	private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);
	private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);

	public Nhacungcap() {
	}

	public Nhacungcap(Khuvuc khuvuc, String ma, String ten, String diachi, String masothue, String fax, String tel,
			String email, String website, String taikhoan, String nganhang, String manguoilienhe, String chucvu,
			Boolean activite, Set<Hanghoa> hanghoas, Set<Phieunhap> phieunhaps) {
		this.khuvuc = khuvuc;
		this.ma = ma;
		this.ten = ten;
		this.diachi = diachi;
		this.masothue = masothue;
		this.fax = fax;
		this.tel = tel;
		this.email = email;
		this.website = website;
		this.taikhoan = taikhoan;
		this.nganhang = nganhang;
		this.manguoilienhe = manguoilienhe;
		this.chucvu = chucvu;
		this.activite = activite;
		this.hanghoas = hanghoas;
		this.phieunhaps = phieunhaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "khuvucid")
	public Khuvuc getKhuvuc() {
		return this.khuvuc;
	}

	public void setKhuvuc(Khuvuc khuvuc) {
		this.khuvuc = khuvuc;
	}

	@Column(name = "ma", length = 20)
	public String getMa() {
		return this.ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}

	@Column(name = "ten")
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "diachi")
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "masothue")
	public String getMasothue() {
		return this.masothue;
	}

	public void setMasothue(String masothue) {
		this.masothue = masothue;
	}

	@Column(name = "fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "tel")
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "website")
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "taikhoan")
	public String getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(String taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "nganhang")
	public String getNganhang() {
		return this.nganhang;
	}

	public void setNganhang(String nganhang) {
		this.nganhang = nganhang;
	}

	@Column(name = "manguoilienhe", length = 20)
	public String getManguoilienhe() {
		return this.manguoilienhe;
	}

	public void setManguoilienhe(String manguoilienhe) {
		this.manguoilienhe = manguoilienhe;
	}

	@Column(name = "chucvu")
	public String getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(String chucvu) {
		this.chucvu = chucvu;
	}

	@Column(name = "activite")
	public Boolean getActivite() {
		return this.activite;
	}

	public void setActivite(Boolean activite) {
		this.activite = activite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhacungcap")
	public Set<Hanghoa> getHanghoas() {
		return this.hanghoas;
	}

	public void setHanghoas(Set<Hanghoa> hanghoas) {
		this.hanghoas = hanghoas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhacungcap")
	public Set<Phieunhap> getPhieunhaps() {
		return this.phieunhaps;
	}

	public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
		this.phieunhaps = phieunhaps;
	}

}
