package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap  implements java.io.Serializable {


     private Integer id;
     private Khuvuc khuvuc;
     private String ma;
     private String ten;
     private String diachi;
     private String masothue;
     private String fax;
     private String tel;
     private String email;
     private String website;
     private String taikhoan;
     private String nganhang;
     private String manguoilienhe;
     private String chucvu;
     private Boolean activite;
     private Set hanghoas = new HashSet(0);
     private Set phieunhaps = new HashSet(0);

    public Nhacungcap() {
    }

    public Nhacungcap(Khuvuc khuvuc, String ma, String ten, String diachi, String masothue, String fax, String tel, String email, String website, String taikhoan, String nganhang, String manguoilienhe, String chucvu, Boolean activite, Set hanghoas, Set phieunhaps) {
       this.khuvuc = khuvuc;
       this.ma = ma;
       this.ten = ten;
       this.diachi = diachi;
       this.masothue = masothue;
       this.fax = fax;
       this.tel = tel;
       this.email = email;
       this.website = website;
       this.taikhoan = taikhoan;
       this.nganhang = nganhang;
       this.manguoilienhe = manguoilienhe;
       this.chucvu = chucvu;
       this.activite = activite;
       this.hanghoas = hanghoas;
       this.phieunhaps = phieunhaps;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Khuvuc getKhuvuc() {
        return this.khuvuc;
    }
    
    public void setKhuvuc(Khuvuc khuvuc) {
        this.khuvuc = khuvuc;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getMasothue() {
        return this.masothue;
    }
    
    public void setMasothue(String masothue) {
        this.masothue = masothue;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(String taikhoan) {
        this.taikhoan = taikhoan;
    }
    public String getNganhang() {
        return this.nganhang;
    }
    
    public void setNganhang(String nganhang) {
        this.nganhang = nganhang;
    }
    public String getManguoilienhe() {
        return this.manguoilienhe;
    }
    
    public void setManguoilienhe(String manguoilienhe) {
        this.manguoilienhe = manguoilienhe;
    }
    public String getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(String chucvu) {
        this.chucvu = chucvu;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }
    public Set getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set hanghoas) {
        this.hanghoas = hanghoas;
    }
    public Set getPhieunhaps() {
        return this.phieunhaps;
    }
    
    public void setPhieunhaps(Set phieunhaps) {
        this.phieunhaps = phieunhaps;
    }




}


