package com.qlbh.pojo;
// Generated 21/09/2016 7:11:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name="nhacungcap"
    ,catalog="qlbh"
)
public class Nhacungcap  implements java.io.Serializable {


     private int ma;
     private Khuvuc khuvuc;
     private String ten;
     private String diachi;
     private String masothue;
     private String fax;
     private String tel;
     private String email;
     private String website;
     private String taikhoan;
     private String nganhang;
     private Integer manguoilienhe;
     private String chucvu;
     private Byte activite;
     private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);
     private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);

    public Nhacungcap() {
    }

	
    public Nhacungcap(int ma) {
        this.ma = ma;
    }
    public Nhacungcap(int ma, Khuvuc khuvuc, String ten, String diachi, String masothue, String fax, String tel, String email, String website, String taikhoan, String nganhang, Integer manguoilienhe, String chucvu, Byte activite, Set<Hanghoa> hanghoas, Set<Phieunhap> phieunhaps) {
       this.ma = ma;
       this.khuvuc = khuvuc;
       this.ten = ten;
       this.diachi = diachi;
       this.masothue = masothue;
       this.fax = fax;
       this.tel = tel;
       this.email = email;
       this.website = website;
       this.taikhoan = taikhoan;
       this.nganhang = nganhang;
       this.manguoilienhe = manguoilienhe;
       this.chucvu = chucvu;
       this.activite = activite;
       this.hanghoas = hanghoas;
       this.phieunhaps = phieunhaps;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="makhuvuc")
    public Khuvuc getKhuvuc() {
        return this.khuvuc;
    }
    
    public void setKhuvuc(Khuvuc khuvuc) {
        this.khuvuc = khuvuc;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="diachi")
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    
    @Column(name="masothue")
    public String getMasothue() {
        return this.masothue;
    }
    
    public void setMasothue(String masothue) {
        this.masothue = masothue;
    }

    
    @Column(name="fax")
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="tel")
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="website")
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }

    
    @Column(name="taikhoan")
    public String getTaikhoan() {
        return this.taikhoan;
    }
    
    public void setTaikhoan(String taikhoan) {
        this.taikhoan = taikhoan;
    }

    
    @Column(name="nganhang")
    public String getNganhang() {
        return this.nganhang;
    }
    
    public void setNganhang(String nganhang) {
        this.nganhang = nganhang;
    }

    
    @Column(name="manguoilienhe")
    public Integer getManguoilienhe() {
        return this.manguoilienhe;
    }
    
    public void setManguoilienhe(Integer manguoilienhe) {
        this.manguoilienhe = manguoilienhe;
    }

    
    @Column(name="chucvu")
    public String getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(String chucvu) {
        this.chucvu = chucvu;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhacungcap")
    public Set<Hanghoa> getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set<Hanghoa> hanghoas) {
        this.hanghoas = hanghoas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhacungcap")
    public Set<Phieunhap> getPhieunhaps() {
        return this.phieunhaps;
    }
    
    public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
        this.phieunhaps = phieunhaps;
    }




}


