package com.qlbh.pojo;
// Generated 25/10/2016 12:14:32 AM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien", catalog = "qlbh")
public class Nhanvien implements java.io.Serializable {

	private Integer id;
	private Bophan bophan;
	private Nhanvien nhanvien;
	private String ma;
	private String ten;
	private String diaChi;
	private Boolean gioiTinh;
	private String chucVu;
	private String email;
	private String dienThoai;
	private Double luong;
	private Boolean activity;
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);
	private Set<Khohang> khohangs = new HashSet<Khohang>(0);
	private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);
	private Set<Nguoidung> nguoidungs = new HashSet<Nguoidung>(0);
	private Set<Phieuxuat> phieuxuats = new HashSet<Phieuxuat>(0);

	public Nhanvien() {
	}

	public Nhanvien(String ma) {
		this.ma = ma;
	}

	public Nhanvien(Bophan bophan, Nhanvien nhanvien, String ma, String ten, String diaChi, Boolean gioiTinh,
			String chucVu, String email, String dienThoai, Double luong, Boolean activity, Set<Nhanvien> nhanviens,
			Set<Khohang> khohangs, Set<Phieunhap> phieunhaps, Set<Nguoidung> nguoidungs, Set<Phieuxuat> phieuxuats) {
		this.bophan = bophan;
		this.nhanvien = nhanvien;
		this.ma = ma;
		this.ten = ten;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.chucVu = chucVu;
		this.email = email;
		this.dienThoai = dienThoai;
		this.luong = luong;
		this.activity = activity;
		this.nhanviens = nhanviens;
		this.khohangs = khohangs;
		this.phieunhaps = phieunhaps;
		this.nguoidungs = nguoidungs;
		this.phieuxuats = phieuxuats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BoPhanId")
	public Bophan getBophan() {
		return this.bophan;
	}

	public void setBophan(Bophan bophan) {
		this.bophan = bophan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NguoiQuanLyID")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Column(name = "Ma", nullable = false, length = 20)
	public String getMa() {
		return this.ma;
	}

	public void setMa(String ma) {
		this.ma = ma;
	}

	@Column(name = "Ten")
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "DiaChi")
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "GioiTinh")
	public Boolean getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "ChucVu")
	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DienThoai")
	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Column(name = "Luong", precision = 65, scale = 0)
	public Double getLuong() {
		return this.luong;
	}

	public void setLuong(Double luong) {
		this.luong = luong;
	}

	@Column(name = "activity")
	public Boolean getActivity() {
		return this.activity;
	}

	public void setActivity(Boolean activity) {
		this.activity = activity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Khohang> getKhohangs() {
		return this.khohangs;
	}

	public void setKhohangs(Set<Khohang> khohangs) {
		this.khohangs = khohangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Phieunhap> getPhieunhaps() {
		return this.phieunhaps;
	}

	public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
		this.phieunhaps = phieunhaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Nguoidung> getNguoidungs() {
		return this.nguoidungs;
	}

	public void setNguoidungs(Set<Nguoidung> nguoidungs) {
		this.nguoidungs = nguoidungs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanvien")
	public Set<Phieuxuat> getPhieuxuats() {
		return this.phieuxuats;
	}

	public void setPhieuxuats(Set<Phieuxuat> phieuxuats) {
		this.phieuxuats = phieuxuats;
	}

	@Override
	public String toString() {
		return this.getTen();
	}

}
