package com.qlbh.pojo;
// Generated 25/10/2016 2:31:22 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Nhatky generated by hbm2java
 */
public class Nhatky implements java.io.Serializable {

	private Integer id;
	private String nguoiDung;
	private String table;
	private String hanhDong;
	private Date ngay;
	private Boolean activity;

	public Nhatky() {
	}

	public Nhatky(String nguoiDung, String table, String hanhDong, Date ngay, Boolean activity) {
		this.nguoiDung = nguoiDung;
		this.table = table;
		this.hanhDong = hanhDong;
		this.ngay = ngay;
		this.activity = activity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(String nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	public String getTable() {
		return this.table;
	}

	public void setTable(String table) {
		this.table = table;
	}

	public String getHanhDong() {
		return this.hanhDong;
	}

	public void setHanhDong(String hanhDong) {
		this.hanhDong = hanhDong;
	}

	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	public Boolean getActivity() {
		return this.activity;
	}

	public void setActivity(Boolean activity) {
		this.activity = activity;
	}

}
