package com.qlbh.pojo;
// Generated 25/10/2016 6:19:56 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhatky generated by hbm2java
 */
@Entity
@Table(name = "nhatky", catalog = "qlbh")
public class Nhatky implements java.io.Serializable {

	private Integer id;
	private String nguoidung;
	private String bang;
	private String hanhdong;
	private Date ngay;
	private Boolean activity;

	public Nhatky() {
	}

	public Nhatky(String nguoidung, String bang, String hanhdong, Date ngay, Boolean activity) {
		this.nguoidung = nguoidung;
		this.bang = bang;
		this.hanhdong = hanhdong;
		this.ngay = ngay;
		this.activity = activity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nguoidung")
	public String getNguoidung() {
		return this.nguoidung;
	}

	public void setNguoidung(String nguoidung) {
		this.nguoidung = nguoidung;
	}

	@Column(name = "bang")
	public String getBang() {
		return this.bang;
	}

	public void setBang(String bang) {
		this.bang = bang;
	}

	@Column(name = "hanhdong")
	public String getHanhdong() {
		return this.hanhdong;
	}

	public void setHanhdong(String hanhdong) {
		this.hanhdong = hanhdong;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay", length = 19)
	public Date getNgay() {
		return this.ngay;
	}

	public void setNgay(Date ngay) {
		this.ngay = ngay;
	}

	@Column(name = "activity")
	public Boolean getActivity() {
		return this.activity;
	}

	public void setActivity(Boolean activity) {
		this.activity = activity;
	}

}
