package com.qlbh.pojo;
// Generated 21/09/2016 7:11:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhomhanghoa generated by hbm2java
 */
@Entity
@Table(name="nhomhanghoa"
    ,catalog="qlbh"
)
public class Nhomhanghoa  implements java.io.Serializable {


     private int ma;
     private String ten;
     private String ghichu;
     private Byte activite;
     private Set<Hanghoa> hanghoas = new HashSet<Hanghoa>(0);

    public Nhomhanghoa() {
    }

	
    public Nhomhanghoa(int ma) {
        this.ma = ma;
    }
    public Nhomhanghoa(int ma, String ten, String ghichu, Byte activite, Set<Hanghoa> hanghoas) {
       this.ma = ma;
       this.ten = ten;
       this.ghichu = ghichu;
       this.activite = activite;
       this.hanghoas = hanghoas;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="ghichu")
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhomhanghoa")
    public Set<Hanghoa> getHanghoas() {
        return this.hanghoas;
    }
    
    public void setHanghoas(Set<Hanghoa> hanghoas) {
        this.hanghoas = hanghoas;
    }




}


