package com.qlbh.pojo;
// Generated 21/09/2016 2:16:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieuxuat generated by hbm2java
 */
@Entity
@Table(name="phieuxuat"
    ,catalog="qlbh"
)
public class Phieuxuat  implements java.io.Serializable {


     private int ma;
     private Khachhang khachhang;
     private Khohang khohang;
     private String diachi;
     private Date ngaygiao;
     private Integer manvbh;
     private Date ngaylap;
     private Double tongtien;
     private Byte activite;
     private Set<Chitietphieuxuat> chitietphieuxuats = new HashSet<Chitietphieuxuat>(0);

    public Phieuxuat() {
    }

	
    public Phieuxuat(int ma) {
        this.ma = ma;
    }
    public Phieuxuat(int ma, Khachhang khachhang, Khohang khohang, String diachi, Date ngaygiao, Integer manvbh, Date ngaylap, Double tongtien, Byte activite, Set<Chitietphieuxuat> chitietphieuxuats) {
       this.ma = ma;
       this.khachhang = khachhang;
       this.khohang = khohang;
       this.diachi = diachi;
       this.ngaygiao = ngaygiao;
       this.manvbh = manvbh;
       this.ngaylap = ngaylap;
       this.tongtien = tongtien;
       this.activite = activite;
       this.chitietphieuxuats = chitietphieuxuats;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="makhachhang")
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="makho")
    public Khohang getKhohang() {
        return this.khohang;
    }
    
    public void setKhohang(Khohang khohang) {
        this.khohang = khohang;
    }

    
    @Column(name="diachi")
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaygiao", length=10)
    public Date getNgaygiao() {
        return this.ngaygiao;
    }
    
    public void setNgaygiao(Date ngaygiao) {
        this.ngaygiao = ngaygiao;
    }

    
    @Column(name="manvbh")
    public Integer getManvbh() {
        return this.manvbh;
    }
    
    public void setManvbh(Integer manvbh) {
        this.manvbh = manvbh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaylap", length=10)
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }

    
    @Column(name="tongtien", precision=22, scale=0)
    public Double getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Double tongtien) {
        this.tongtien = tongtien;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phieuxuat")
    public Set<Chitietphieuxuat> getChitietphieuxuats() {
        return this.chitietphieuxuats;
    }
    
    public void setChitietphieuxuats(Set<Chitietphieuxuat> chitietphieuxuats) {
        this.chitietphieuxuats = chitietphieuxuats;
    }




}


