package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieunhap generated by hbm2java
 */
public class Phieunhap  implements java.io.Serializable {


     private Integer id;
     private Khohang khohang;
     private Nhacungcap nhacungcap;
     private Nhanvien nhanvien;
     private String ma;
     private Date ngaynhap;
     private Double tongtien;
     private Boolean activite;
     private Set chitietphieunhaps = new HashSet(0);

    public Phieunhap() {
    }

    public Phieunhap(Khohang khohang, Nhacungcap nhacungcap, Nhanvien nhanvien, String ma, Date ngaynhap, Double tongtien, Boolean activite, Set chitietphieunhaps) {
       this.khohang = khohang;
       this.nhacungcap = nhacungcap;
       this.nhanvien = nhanvien;
       this.ma = ma;
       this.ngaynhap = ngaynhap;
       this.tongtien = tongtien;
       this.activite = activite;
       this.chitietphieunhaps = chitietphieunhaps;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Khohang getKhohang() {
        return this.khohang;
    }
    
    public void setKhohang(Khohang khohang) {
        this.khohang = khohang;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public Date getNgaynhap() {
        return this.ngaynhap;
    }
    
    public void setNgaynhap(Date ngaynhap) {
        this.ngaynhap = ngaynhap;
    }
    public Double getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Double tongtien) {
        this.tongtien = tongtien;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }
    public Set getChitietphieunhaps() {
        return this.chitietphieunhaps;
    }
    
    public void setChitietphieunhaps(Set chitietphieunhaps) {
        this.chitietphieunhaps = chitietphieunhaps;
    }




}


