package com.qlbh.pojo;
// Generated 21/10/2016 11:19:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieuxuat generated by hbm2java
 */
public class Phieuxuat  implements java.io.Serializable {


     private Integer id;
     private Khachhang khachhang;
     private Khohang khohang;
     private Nhanvien nhanvien;
     private String ma;
     private String diachi;
     private Date ngaygiao;
     private Date ngaylap;
     private String dienthoai;
     private Double tongtien;
     private String ghichu;
     private Boolean activity;
     private Set chitietphieuxuats = new HashSet(0);

    public Phieuxuat() {
    }

    public Phieuxuat(Khachhang khachhang, Khohang khohang, Nhanvien nhanvien, String ma, String diachi, Date ngaygiao, Date ngaylap, String dienthoai, Double tongtien, String ghichu, Boolean activity, Set chitietphieuxuats) {
       this.khachhang = khachhang;
       this.khohang = khohang;
       this.nhanvien = nhanvien;
       this.ma = ma;
       this.diachi = diachi;
       this.ngaygiao = ngaygiao;
       this.ngaylap = ngaylap;
       this.dienthoai = dienthoai;
       this.tongtien = tongtien;
       this.ghichu = ghichu;
       this.activity = activity;
       this.chitietphieuxuats = chitietphieuxuats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Khohang getKhohang() {
        return this.khohang;
    }
    
    public void setKhohang(Khohang khohang) {
        this.khohang = khohang;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Date getNgaygiao() {
        return this.ngaygiao;
    }
    
    public void setNgaygiao(Date ngaygiao) {
        this.ngaygiao = ngaygiao;
    }
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }
    public String getDienthoai() {
        return this.dienthoai;
    }
    
    public void setDienthoai(String dienthoai) {
        this.dienthoai = dienthoai;
    }
    public Double getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Double tongtien) {
        this.tongtien = tongtien;
    }
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
    public Set getChitietphieuxuats() {
        return this.chitietphieuxuats;
    }
    
    public void setChitietphieuxuats(Set chitietphieuxuats) {
        this.chitietphieuxuats = chitietphieuxuats;
    }




}


