package com.qlbh.pojo;
// Generated 21/09/2016 2:16:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieunhap generated by hbm2java
 */
@Entity
@Table(name="phieunhap"
    ,catalog="qlbh"
)
public class Phieunhap  implements java.io.Serializable {


     private int ma;
     private Khohang khohang;
     private Nhacungcap nhacungcap;
     private Integer manvn;
     private Date ngaynhap;
     private Double tongtien;
     private Byte activite;
     private Set<Chitietphieunhap> chitietphieunhaps = new HashSet<Chitietphieunhap>(0);

    public Phieunhap() {
    }

	
    public Phieunhap(int ma) {
        this.ma = ma;
    }
    public Phieunhap(int ma, Khohang khohang, Nhacungcap nhacungcap, Integer manvn, Date ngaynhap, Double tongtien, Byte activite, Set<Chitietphieunhap> chitietphieunhaps) {
       this.ma = ma;
       this.khohang = khohang;
       this.nhacungcap = nhacungcap;
       this.manvn = manvn;
       this.ngaynhap = ngaynhap;
       this.tongtien = tongtien;
       this.activite = activite;
       this.chitietphieunhaps = chitietphieunhaps;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="makho")
    public Khohang getKhohang() {
        return this.khohang;
    }
    
    public void setKhohang(Khohang khohang) {
        this.khohang = khohang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manhacc")
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }

    
    @Column(name="manvn")
    public Integer getManvn() {
        return this.manvn;
    }
    
    public void setManvn(Integer manvn) {
        this.manvn = manvn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaynhap", length=10)
    public Date getNgaynhap() {
        return this.ngaynhap;
    }
    
    public void setNgaynhap(Date ngaynhap) {
        this.ngaynhap = ngaynhap;
    }

    
    @Column(name="tongtien", precision=22, scale=0)
    public Double getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Double tongtien) {
        this.tongtien = tongtien;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phieunhap")
    public Set<Chitietphieunhap> getChitietphieunhaps() {
        return this.chitietphieunhaps;
    }
    
    public void setChitietphieunhaps(Set<Chitietphieunhap> chitietphieunhaps) {
        this.chitietphieunhaps = chitietphieunhaps;
    }




}


