package com.qlbh.pojo;
// Generated 21/10/2016 11:56:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tygia generated by hbm2java
 */
@Entity
@Table(name="tygia", catalog="qlbh")
public class Tygia  implements java.io.Serializable {
	private Integer id;
	private String ma;
	private String ten;
	private Float tygiaquydoi;
	private Boolean activity;

    public Tygia() {
    }

    public Tygia(String ma, String ten, Float tygiaquydoi, Boolean activity) {
       this.ma = ma;
       this.ten = ten;
       this.tygiaquydoi = tygiaquydoi;
       this.activity = activity;
    }
   
    @Id
    @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ma", length=20)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="tygiaquydoi", precision=4, scale=0)
    public Float getTygiaquydoi() {
        return this.tygiaquydoi;
    }
    
    public void setTygiaquydoi(Float tygiaquydoi) {
        this.tygiaquydoi = tygiaquydoi;
    }

    
    @Column(name="activity")
    public Boolean getActivity() {
        return this.activity;
    }
    
    public void setActivity(Boolean activity) {
        this.activity = activity;
    }
}


