package com.qlbh.pojo;
// Generated 24/09/2016 3:20:15 PM by Hibernate Tools 4.3.1



/**
 * Tygia generated by hbm2java
 */
public class Tygia  implements java.io.Serializable {


     private Integer id;
     private String ma;
     private String ten;
     private Float tygiaquydoi;
     private Boolean activite;

    public Tygia() {
    }

    public Tygia(String ma, String ten, Float tygiaquydoi, Boolean activite) {
       this.ma = ma;
       this.ten = ten;
       this.tygiaquydoi = tygiaquydoi;
       this.activite = activite;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public Float getTygiaquydoi() {
        return this.tygiaquydoi;
    }
    
    public void setTygiaquydoi(Float tygiaquydoi) {
        this.tygiaquydoi = tygiaquydoi;
    }
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }




}


