package com.qlbh.pojo;
// Generated 23/09/2016 10:02:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vaitro generated by hbm2java
 */
@Entity
@Table(name="vaitro"
    ,catalog="qlbh"
)
public class Vaitro  implements java.io.Serializable {


     private Integer id;
     private Vaitro vaitro;
     private String ma;
     private String ten;
     private String diengiai;
     private Boolean truycap;
     private Boolean them;
     private Boolean xem;
     private Boolean xoa;
     private Boolean sua;
     private Boolean in;
     private Boolean nhap;
     private Boolean xuat;
     private Boolean activite;
     private Set<Vaitro> vaitros = new HashSet<Vaitro>(0);
     private Set<Nguoidung> nguoidungs = new HashSet<Nguoidung>(0);

    public Vaitro() {
    }

    public Vaitro(Vaitro vaitro, String ma, String ten, String diengiai, Boolean truycap, Boolean them, Boolean xem, Boolean xoa, Boolean sua, Boolean in, Boolean nhap, Boolean xuat, Boolean activite, Set<Vaitro> vaitros, Set<Nguoidung> nguoidungs) {
       this.vaitro = vaitro;
       this.ma = ma;
       this.ten = ten;
       this.diengiai = diengiai;
       this.truycap = truycap;
       this.them = them;
       this.xem = xem;
       this.xoa = xoa;
       this.sua = sua;
       this.in = in;
       this.nhap = nhap;
       this.xuat = xuat;
       this.activite = activite;
       this.vaitros = vaitros;
       this.nguoidungs = nguoidungs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vaitrochaid")
    public Vaitro getVaitro() {
        return this.vaitro;
    }
    
    public void setVaitro(Vaitro vaitro) {
        this.vaitro = vaitro;
    }

    
    @Column(name="ma", length=20)
    public String getMa() {
        return this.ma;
    }
    
    public void setMa(String ma) {
        this.ma = ma;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="diengiai")
    public String getDiengiai() {
        return this.diengiai;
    }
    
    public void setDiengiai(String diengiai) {
        this.diengiai = diengiai;
    }

    
    @Column(name="truycap")
    public Boolean getTruycap() {
        return this.truycap;
    }
    
    public void setTruycap(Boolean truycap) {
        this.truycap = truycap;
    }

    
    @Column(name="them")
    public Boolean getThem() {
        return this.them;
    }
    
    public void setThem(Boolean them) {
        this.them = them;
    }

    
    @Column(name="xem")
    public Boolean getXem() {
        return this.xem;
    }
    
    public void setXem(Boolean xem) {
        this.xem = xem;
    }

    
    @Column(name="xoa")
    public Boolean getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Boolean xoa) {
        this.xoa = xoa;
    }

    
    @Column(name="sua")
    public Boolean getSua() {
        return this.sua;
    }
    
    public void setSua(Boolean sua) {
        this.sua = sua;
    }

    
    @Column(name="in")
    public Boolean getIn() {
        return this.in;
    }
    
    public void setIn(Boolean in) {
        this.in = in;
    }

    
    @Column(name="nhap")
    public Boolean getNhap() {
        return this.nhap;
    }
    
    public void setNhap(Boolean nhap) {
        this.nhap = nhap;
    }

    
    @Column(name="xuat")
    public Boolean getXuat() {
        return this.xuat;
    }
    
    public void setXuat(Boolean xuat) {
        this.xuat = xuat;
    }

    
    @Column(name="activite")
    public Boolean getActivite() {
        return this.activite;
    }
    
    public void setActivite(Boolean activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vaitro")
    public Set<Vaitro> getVaitros() {
        return this.vaitros;
    }
    
    public void setVaitros(Set<Vaitro> vaitros) {
        this.vaitros = vaitros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vaitro")
    public Set<Nguoidung> getNguoidungs() {
        return this.nguoidungs;
    }
    
    public void setNguoidungs(Set<Nguoidung> nguoidungs) {
        this.nguoidungs = nguoidungs;
    }




}


