package com.qlbh.pojo;
// Generated 21/09/2016 2:16:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vaitro generated by hbm2java
 */
@Entity
@Table(name="vaitro"
    ,catalog="qlbh"
)
public class Vaitro  implements java.io.Serializable {


     private int ma;
     private Vaitro vaitro;
     private String ten;
     private String diengiai;
     private Byte truycap;
     private Byte them;
     private Byte xem;
     private Byte xoa;
     private Byte sua;
     private Byte in;
     private Byte nhap;
     private Byte xuat;
     private Byte activite;
     private Set<Nguoidung> nguoidungs = new HashSet<Nguoidung>(0);
     private Set<Vaitro> vaitros = new HashSet<Vaitro>(0);

    public Vaitro() {
    }

	
    public Vaitro(int ma) {
        this.ma = ma;
    }
    public Vaitro(int ma, Vaitro vaitro, String ten, String diengiai, Byte truycap, Byte them, Byte xem, Byte xoa, Byte sua, Byte in, Byte nhap, Byte xuat, Byte activite, Set<Nguoidung> nguoidungs, Set<Vaitro> vaitros) {
       this.ma = ma;
       this.vaitro = vaitro;
       this.ten = ten;
       this.diengiai = diengiai;
       this.truycap = truycap;
       this.them = them;
       this.xem = xem;
       this.xoa = xoa;
       this.sua = sua;
       this.in = in;
       this.nhap = nhap;
       this.xuat = xuat;
       this.activite = activite;
       this.nguoidungs = nguoidungs;
       this.vaitros = vaitros;
    }
   
     @Id 

    
    @Column(name="ma", unique=true, nullable=false)
    public int getMa() {
        return this.ma;
    }
    
    public void setMa(int ma) {
        this.ma = ma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mavaitrocha")
    public Vaitro getVaitro() {
        return this.vaitro;
    }
    
    public void setVaitro(Vaitro vaitro) {
        this.vaitro = vaitro;
    }

    
    @Column(name="ten")
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }

    
    @Column(name="diengiai")
    public String getDiengiai() {
        return this.diengiai;
    }
    
    public void setDiengiai(String diengiai) {
        this.diengiai = diengiai;
    }

    
    @Column(name="truycap")
    public Byte getTruycap() {
        return this.truycap;
    }
    
    public void setTruycap(Byte truycap) {
        this.truycap = truycap;
    }

    
    @Column(name="them")
    public Byte getThem() {
        return this.them;
    }
    
    public void setThem(Byte them) {
        this.them = them;
    }

    
    @Column(name="xem")
    public Byte getXem() {
        return this.xem;
    }
    
    public void setXem(Byte xem) {
        this.xem = xem;
    }

    
    @Column(name="xoa")
    public Byte getXoa() {
        return this.xoa;
    }
    
    public void setXoa(Byte xoa) {
        this.xoa = xoa;
    }

    
    @Column(name="sua")
    public Byte getSua() {
        return this.sua;
    }
    
    public void setSua(Byte sua) {
        this.sua = sua;
    }

    
    @Column(name="in")
    public Byte getIn() {
        return this.in;
    }
    
    public void setIn(Byte in) {
        this.in = in;
    }

    
    @Column(name="nhap")
    public Byte getNhap() {
        return this.nhap;
    }
    
    public void setNhap(Byte nhap) {
        this.nhap = nhap;
    }

    
    @Column(name="xuat")
    public Byte getXuat() {
        return this.xuat;
    }
    
    public void setXuat(Byte xuat) {
        this.xuat = xuat;
    }

    
    @Column(name="activite")
    public Byte getActivite() {
        return this.activite;
    }
    
    public void setActivite(Byte activite) {
        this.activite = activite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vaitro")
    public Set<Nguoidung> getNguoidungs() {
        return this.nguoidungs;
    }
    
    public void setNguoidungs(Set<Nguoidung> nguoidungs) {
        this.nguoidungs = nguoidungs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vaitro")
    public Set<Vaitro> getVaitros() {
        return this.vaitros;
    }
    
    public void setVaitros(Set<Vaitro> vaitros) {
        this.vaitros = vaitros;
    }




}


